# Generated by Django 4.2.29 on 2026-06-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DriverOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='DriverOS.carprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DrowsinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ear_value', models.FloatField()),
                ('alert_triggered', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drowsiness_events', to='DriverOS.drivesession')),
            ],
        ),
    ]
