# Generated by Django 4.2.29 on 2026-06-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DriverOS', '0002_drivesession_drowsinessevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('start_location', models.CharField(blank=True, max_length=255)),
                ('end_location', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='DriverOS.carprofile')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('odometer_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('upcoming', 'Upcoming')], default='done', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='DriverOS.carprofile')),
            ],
            options={
                'ordering': ['status', 'next_due_date', 'next_due_odometer', '-service_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelFillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_at', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_reading', models.PositiveIntegerField()),
                ('station', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_fill_logs', to='DriverOS.carprofile')),
            ],
            options={
                'ordering': ['-filled_at', '-odometer_reading', '-created_at'],
            },
        ),
    ]
